add two class Category and Product
AndyTums/MyProjectClass pull request #1
Opened 2024-07-22 19:48 UTC by AndyTums

Start new Homework 14.1

2024-07-23 09:29 UTC, painassasin requested changes

2024-07-23 09:29 UTC, painassasin commented on htmlcov/class_index.html
результаты coverage на github не выкладываем

2024-07-23 09:29 UTC, painassasin commented on src/main.py
> +class Category():
Тут скобочки лишние, пишем просто `Category:`

2024-07-23 09:29 UTC, painassasin commented on src/main.py
> +    name: str
Тайпхинты нужно указывать в методе init
```python
class Category:

    category_count = 0
    product_count = 0

    def __init__(self, name: str, description: str, products: list = None) -> None:
        self.name = name
        self.description = description
        self.products = products
        Category.category_count += 1
        Category.product_count += len(self.products)
```

2024-07-23 09:29 UTC, painassasin commented on tests/conftest.py
> +def one_category():
Раз ты используешь продукт из фикстуры, то правильнее будет так
```python
@pytest.fixture
def one_category(one_product):
    return Category(
         name="Смартфоны",
         description=(
             "Смартфоны, как средство не только коммуникации, "
             "но и получения дополнительных функций для удобства жизни"
         ),
         products=[one_product]
    )

2024-07-23 09:29 UTC, painassasin commented on src/main.py
Модели с данными нужно указывать в отдельном модуле, например models.py

А в файле main.py будет исполняемый код, причем этот файл (main.py) лучше перенести в корень, чтобы было удобно запускать проект из консоли

2024-07-23 18:48 UTC, AndyTums commented on htmlcov/class_index.html
В репозитории есть папка с отчетом покрытия тестами в формате HTML. - ТЗ

2024-07-24 11:13 UTC, painassasin requested changes

2024-07-24 11:13 UTC, painassasin commented on src/models.py
> +    def __init__(self, name, description, price, quantity):
Тайпхинты нужно указать в этом методе, а не в атрибутах класса

2024-07-24 11:13 UTC, painassasin commented on src/models.py
> +    def __init__(self, name, description, products):
Тут тоже тайпхинты на метод нужно перенести

2024-07-24 11:13 UTC, painassasin commented on src/utils.py
> +# reding_file = read_json("../data/products.json")
Закомментированный код нужно удалить

2024-07-25 08:27 UTC, painassasin requested changes

2024-07-25 08:27 UTC, painassasin commented on src/models.py
> +    name: str
С 20 по 22 строки нужно удалить

2024-07-25 08:27 UTC, painassasin commented on src/models.py
> +    name: str
с 4 по 7 строки нужно удалить

2024-07-26 11:45 UTC, painassasin approved these changes

2024-07-30 10:03 UTC, merged